### ISSUE TITLE
S3 connector update for milestone 2 (run the whole docker)

### ISSUE THREAD

**Issue by celine3650** [filecoin-project/motion#113]
Update the docker file. https://github.com/filecoin-project/motion-s3-connector

**Comment by masih** [comment]
To clarify, the ask here is to:
* change the existing motion s3 connector to stand up singularity with motion configured to talk to it. 
* the changes would then require the user to supply a wallet key with pre-existing funds and a valid storage provider address on mainnet.

@celine3650 please let me know if this is consistent with your understanding.

**Comment by celine3650** [comment]
Pending a PR review.
