### ISSUE TITLE
Report the latest deal check timestamp from Singularity as `LastVerified`

### ISSUE THREAD

**Issue by masih** [filecoin-project/motion#132]
Singularity periodically scans the deals snapshot data from the  S3  endpoint; report the latest timestamp at which the check was performed as `LastVerified` in Motion.

Eventually, checks in Singularity should become more sophisticated to include latest timestamp of proof of replicaiton on chain. However, from Motion perspective reporting the date remains the same: the check timestamp comes from singularity and what the check means is dictated by Singularity.

Relates to #66

**Comment by elijaharita** [comment]
is this info already exposed by singularity or is it going to take a change there first?

**Comment by xinaxu** [comment]
Singularity will need to add a column for this timestamp first.
@masih 
> Eventually, checks in Singularity should become more sophisticated to include latest timestamp of proof of replicaiton on chain.

Are we thinking about including the proof of replication as the same call or as part of a separate diagnose API

**Comment by masih** [comment]
@xinaxu Thank you for folagging.

 I think the `Deal` entity in Singularity already has a `UpdatedAt` field which is also updated as [part of deal tracking](https://github.com/data-preservation-programs/singularity/blob/753cdba620460d4b24880d64aad00e5ae37bf00b/service/dealtracker/dealtracker.go#L487). Right?

I understand that the `UpdatedAt` timestamp does not directly represent verification timestamp, but it is a good first iteration considering we return zero-value time right now.

Once checks in signularity get more sophisticated and that timestamp gets separated then it should be a straightforward change in motion: we would simply return a different field instead of `UpdatedAt`.

I'll capture separate issues for refining this in Signularity. 

In the meantime is there anything else that is blocking this issue @elijaharita @xinaxu ?

**Comment by xinaxu** [comment]
Makes sense to me
