### ISSUE TITLE
No deals are created after 40 GiB of data upload

### ISSUE THREAD

**Issue by masih** [filecoin-project/motion#141]
During testing @elijaharita uploaded 40 GiB of data to devnet for which no deals were captured. understand why

**Comment by elijaharita** [comment]
to add more info about what i think should happen:

i think that the blob status endpoint should always show why a deal has not been made, if the quota has not been met yet.

possible reasons i can immediately think of, in the order they should be checked

1. no SPs are configured
2. not enough data has been pushed
3. ready for deal but has not been attempted yet
4. deal was attempted but failed

anything missing?

**Comment by masih** [comment]
@elijaharita is this still an issue after #140 is fixed? Might be worth giving the head of main a try before further investigation.

**Comment by elijaharita** [comment]
@masih good idea, i'll try it out

**Comment by elijaharita** [comment]
working now.

diagnostics might still be useful sometime in the future
