### ISSUE TITLE
DWS Alpha testing version issue

### ISSUE THREAD

**Issue by celine3650** [filecoin-project/motion#161]
SINGULARITY_REF=:v0.4.1 is missing, this version is specified in your .env.example file in the motion repo and I’m getting “manifest unknown error” from Docker when I try to pull this image. Should I use another version for testing?

**Comment by masih** [comment]
Retry with the head of main? the current version is updated to v0.5.1.

**Comment by xinaxu** [comment]
Republished v0.4.1
https://github.com/data-preservation-programs/singularity/pkgs/container/singularity/138339955?tag=v0.4.1

However, as masih suggested, please use the latest version v0.5.1
