### ISSUE TITLE
Wallet management

### ISSUE THREAD

**Issue by willscott** [filecoin-project/motion#17]
Need a way to specify a wallet for use in motion as part of config / startup

may be blocked on #16 

Definition of done:
- Wallet configurable in local yaml of docker deployment ready to test by users

**Comment by TorfinnOlsen** [comment]
Will is it reasonable to expect that the MVP motion users will be able to configure their wallet addresses or is this something that we'll hardcode for the sake of testing the MVP?

**Comment by willscott** [comment]
define 'configure' - i would expect they would put their wallet information in a config file / docker environment variable.

**Comment by masih** [comment]
I think we would take path to private key or something along those lines. 
For the MVP, one wallet will be used for all storage deals.

**Comment by TorfinnOlsen** [comment]
One wallet for MVP seems reasonable to me and a lot less work I'm going to call that out on the one pager and let product challenge the assertion.

**Comment by masih** [comment]
Already marked as done on the project board. Closing.
