### ISSUE TITLE
As an ISV storing user data, I should be able to retrieve bytes I previously stored

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/motion#18]
This issue tracks work needed to implement the retrieval API

Initial Requirements:
- [ ] Agree on how the singularity model maps to the motion domain model - specifically, which Singularity object are we using to represent Blobs (Dataset, Source, Directory, or Item) (TShirt Size: 1)
- [ ] Insure the singularity model contains all of the information required to identify CIDS that make up a blob. Build a function that says given a Blob ID, determine it's CIDs (TShirt Size: 2)
- [ ] Find mechanism to identify what deals contain a given CID.
   - [ ] Insure Blobs and CIDs in a blob can be linked to tracked Deals in Singularity (not currently possible-https://github.com/data-preservation-programs/singularity/issues/71). (TShirt Size: 1)
   - Build a function that says given a CID, determine what deals its in (TShirt Size: 2)
- [ ] Build multi-part retrieval into Lassie (or, alternatively just put it in Motion, though it would be great for this to be in Lassie) (TShirt Size: 3)
- [ ] Use Lassie backed by custom content discoverty to build a Block retrieval function (Tshirt Size: 2)

**Comment by celine3650** [comment]
@hannahhoward Hey Hannah, you mentioned there is a newer item related to this retrieve API, can you share the issue ticket?

**Comment by celine3650** [comment]
Found it. [https://github.com/data-preservation-programs/singularity/issues/113]
