### ISSUE TITLE
[Beta Testing with SPs] Confirm pull-mode storage deal configuration is set up to test Filswan

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/motion#182]
Run our test Motion instance with pull-mode storage deals for SPs. Confirm SP configuration is set up to import deal data. cc @xinaxu @rvagg

**Comment by rvagg** [comment]
👍 

we had a bit of trouble making deals but have sorted out some bugs along the way. Notably https://github.com/data-preservation-programs/singularity/pull/413 for proposing usable deals and https://github.com/data-preservation-programs/singularity/pull/416 for serving pieces; plus a couple of problems on the other side too but we seem to be underway now
