### ISSUE TITLE
[Beta Testing with SPs] Confirm Motion test instance IP address

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/motion#183]
Send the IP address of our test Motion instance to be put on the allowlist for SPs to accept our storage deals.

**Comment by rvagg** [comment]
Let's go with `3.12.105.72`, @davidd8 || @xinaxu can you pass this on to the relevant people please? We'll hang on to this elastic IP as long as we need it and associate it with whatever motion instance(s) we're testing with.

**Comment by davidd8** [comment]
Added, thank you!
