### ISSUE TITLE
[Beta Testing with SPs] Write storage script

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/motion#184]
Write a test script for SPs that stores ~100GB to Motion to then be stored on the SP via a storage deal on Filecoin. May need to track important CIDs of the data to retrieve later on.

Assume this script will be used multiple times for each SP onboarded to Motion.

**Comment by rvagg** [comment]
Documented in private page titled "Production Motion SP Testing" in PL Ecosystem Notion under "Project Motion"

Code to operate and monitor Motion from the outside is here: https://github.com/filecoin-project/motion-sp-test
