### ISSUE TITLE
[Beta Testing with SPs] Write Status Script

### ISSUE THREAD

**Issue by davidd8** [filecoin-project/motion#185]
Write a test script for SPs that uses the Motion status API to confirm the blobs have been stored on Filecoin to the SPs in question.

Assume this script will be used multiple times for each SP onboarded to Motion.

**Comment by rvagg** [comment]
Documented in private page titled "Production Motion SP Testing" in PL Ecosystem Notion under "Project Motion"

https://github.com/filecoin-project/motion-sp-test is intended to monitor Motion from the outside and track status over time and record status change timestamps .. still waiting in "proposed" state as I write this but hopefully we'll move beyond that soon.
