### ISSUE TITLE
Policy / Config specification / translation

### ISSUE THREAD

**Issue by willscott** [filecoin-project/motion#19]
we need to decide what is exposed to an ISV, and then translate that into a working singularity config/policy for deal making.

**Comment by willscott** [comment]
need at least
* pool of SPs to use
* wallet
* how many replicas to aim for
* how much we're willing to pay (if any)
* how long to make deals for

**Comment by masih** [comment]
Documenting the config granularity requirements: For the MVP all such parameters will be global.

**Comment by davidd8** [comment]
Global for each client, or deployment of Motion?

**Comment by masih** [comment]
Per Deployment

**Comment by davidd8** [comment]
So to be clear, in the MVP, the ISV will use the same wallet to store data for every client across the same sets of SPs with the same replication factor.

**Comment by masih** [comment]
That's consistent with my understanding for the MVP.

**Comment by willscott** [comment]
The singularity config isn't in a single struct, but options are enumerated in the CLI documentation: https://github.com/data-preservation-programs/singularity/tree/74a7d590d08ae66c0781a2220bc250a1a65a4d41/docs/en/cli-reference
