### ISSUE TITLE
SingularityContentURLTemplate does not include `http://`

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/motion#207]
```
deal rejected: server error: get deal transfer host: cannot parse url
'3.12.105.72:7778/piece/baga6ea4seaqeuoaye2afs6a36jvisqaam6i4vt45htbt2cjdmo2n32cgqhfpuky': parsing url
'3.12.105.72:7778/piece/baga6ea4seaqeuoaye2afs6a36jvisqaam6i4vt45htbt2cjdmo2n32cgqhfpuky': parse
"3.12.105.72:7778/piece/baga6ea4seaqeuoaye2afs6a36jvisqaam6i4vt45htbt2cjdmo2n32cgqhfpuky\":
first path segment in URL cannot contain colon
```

This comes from SINGULARITY_CONTENT_PROVIDER_DOMAIN which is documented to just be host:port, not full URL, so somethings hiccuping in here and not prefixing `http`?

Please investigate if this is a documentation issue or a code bug.

**Comment by rvagg** [comment]
See also https://github.com/data-preservation-programs/singularity/issues/411

**Comment by gammazero** [comment]
This and https://github.com/data-preservation-programs/singularity/issues/411 are duplicates.  Let's decide where we want to fix this.  I am recommending we fix it in singularity, because:

> Since a template may contain any number of values to replace, even the scheme portion of the URL, checking for a correct URL should be done after template values are replaced. This is why this is being fixed in singularity, after the point the template is evaluated.
