### ISSUE TITLE
Decide on structure for deal prep

### ISSUE THREAD

**Issue by willscott** [filecoin-project/motion#23]
before implementation we should compare options and choose a path for how received data gets sliced/converted into deals.

* ribs [carlog](https://github.com/FILCAT/ribs/blob/main/carlog/carlog.go)
* singularity v2 [pack](https://github.com/data-preservation-programs/singularity/tree/main/pack)
* singularity v1 [generate car](https://github.com/tech-greedy/generate-car)

**Comment by TorfinnOlsen** [comment]
Leaving a note here to call out @masih's comment that we're going to need to accommodate ISV's making deals we don't want announced to IPNI.

**Comment by marinakosti** [comment]
@TorfinnOlsen @willscott what does each option mean for user (MSP/ ISV or SP) user experience?

**Comment by willscott** [comment]
there should not be a meaningful difference in user experience. this is more about which code base we focus effort on to raise to a reliability and test level we are comfortable with.
