### ISSUE TITLE
Set up Integration testing environment

### ISSUE THREAD

**Issue by masih** [filecoin-project/motion#27]
Set up a reproducible integration testing environment such that we can test the Motion API against a devnet instance of boost and verify that the end to end storage and retrieval works. 

Definition of Done:

- perform a devnet deal with FIL

**Comment by TorfinnOlsen** [comment]
FYI @kylehuntsman during a meeting with Lauren today we talked about end to end integration testing and discussed that making deals with FILCollins should be on the table.

**Comment by TorfinnOlsen** [comment]
@kylehuntsman just to be clear this issue is with respect to actually setting up a repeatable test environment we can use to execute tests.

**Comment by celine3650** [comment]
It's a duplicate as the #60
