### ISSUE TITLE
Add REST API tests

### ISSUE THREAD

**Issue by masih** [filecoin-project/motion#28]
Add black box testing for the REST APIs that assert the API exposed by Motion conforms to its open API specification. This should work entirely locally in first iteration but be runnable against a given Motion endpoint for future integration and conformant testing.

**Comment by elijaharita** [comment]
what form do we want this to take? we don't have a generated api, right? so should it just be hand-written http calls in _test.go file?

**Comment by masih** [comment]
> hand-written http calls in _test.go file?

Yep. Something like [this](https://github.com/ipni/dhstore/blob/main/server/server_test.go#L27)
