### ISSUE TITLE
Secure a wallet with ~50Fil / Datacap for making verified deals

### ISSUE THREAD

**Issue by TorfinnOlsen** [filecoin-project/motion#33]
Torfinn secure a wallet from Finops with 50Fil for testing and accumulate some data cap to test with.

**Comment by TorfinnOlsen** [comment]
Wallet secured: shared with team on 1password, Finops advised they are distributing 50FIL to the wallet but upon checking the chain status the 50FIL is still not there, have reached out to the Finops team for an update.

**Comment by willscott** [comment]
@TorfinnOlsen  you should be able to get some automatic datacap on the address with https://verify.glif.io/

**Comment by TorfinnOlsen** [comment]
Wallet address - distributed to team members in 1Pass, pending allocation from finops team(they've advised it's in process). f3vhlf4yh4n7aurqx7hsjwumzyyfnr2f64rmci77f2jon6eil7cdwhaekkcs42dem3gsodumvme4ma67y3m4vq

**Comment by TorfinnOlsen** [comment]
Got feedback from finops they'll have funds dispersed this week.

**Comment by celine3650** [comment]
Pending finops to get back to the wallet info.

**Comment by celine3650** [comment]
The wallet is deposited.
