### ISSUE TITLE
Integration test for S3 Compliant API

### ISSUE THREAD

**Issue by TorfinnOlsen** [filecoin-project/motion#34]
Could be a docker Compose, but basically we want an end to end test in order to validate the S3 connector.

This is the actual bash or otherwise integration test we could manually run against the connector now to validate that it works. 

Adding items from meeting for followup to complete S3 Compliant API test: 

Status of mounting the volume(persistence).
- How can we handle ISV AWS creds for testing? Lauren mentioned a concern that there might be a blocker with the way this is handled in Zenko, but we basically need to think through how we're doing it and get to the bottom of whether or not there is a risk.

- Lastly, once we've figured that out we need to brush up the documentation for describing how ISV's can incorporate their own creds into the connector test, so that we can share it with them and start testing!

**Comment by TorfinnOlsen** [comment]
Possibly overlaps with #27 , although I do think there are technically 2 unique tasks here. If you want to combine them I think that's ok too!

**Comment by TorfinnOlsen** [comment]
DWS tested the connector, and created an issue here: https://github.com/filecoin-project/motion/issues/49 

Issue expected to be fixed during implementation of features in Milestone 2.

**Comment by celine3650** [comment]
The uploadPart operation will be supported in beta not milestone 2.
