### ISSUE TITLE
Flush of transient data

### ISSUE THREAD

**Issue by willscott** [filecoin-project/motion#36]
the motion api needs to be extended in a way that we can give an ISV away to indicate that they would like to "flush" data to durable storage.

There may otherwise be times where an ISV has finished one data set and does not immediately want to start another one, or that they want to drain the motion docker container and move it to another node.

We need to enable them to signal that to us, and to be able to subsequently indicate (perhaps the existing status endpoint is sufficient) that it is safe to tear down the motion instance.

**Comment by davidd8** [comment]
A lot of this can be pushed to a post-M3 milestone. The Motion DB should be durable enough for testing, and the ISV features are more geared for sophisticated deployments (many clients, etc.). Let's set some decent heuristics for when to automatically store on Filecoin, but the MVP should be considered best-effort during the M2 milestone.

**Comment by willscott** [comment]
I think we may want this for testing earlier to have deterministic behavior

**Comment by masih** [comment]
The simplest most managable policy I can think of, which at the same time remains useful to the user, is: 
* The data will be retained as long as a blob ID is returned in response to `POST /v0/blob`. If no such ID is returned, all bets are off.

@willscott does that sound reasonable?

**Comment by willscott** [comment]
Imagine i upload my TB dataset, and it's not 32gB aligned so i end up with a dangling 10GB of data that just stays in the motion container.

i may want to get durability of that final chunk of data beyond the local container.
Imagine for instance i'm doing backups weekly - i don't want to not have that data backed up for a week

**Comment by masih** [comment]
That's fine. 

The question for me is where do we draw the line on whether or not the data is received by Motion?

**Comment by willscott** [comment]
* having the post call not return for a week seems not like the expected behavior
* we could have an implicit flush - e.g. after an hour/<configurable period> of inactivity

**Comment by masih** [comment]
Why would post not return for a week if the maximum accepted blob size for the MVP is 31GiB?

There is an implicit assumption I am making here which is retuning 200 with ID is independent of deals being made/accepted on Filecoin network.

**Comment by willscott** [comment]
by flush here i mean:
"all data managed by motion is replicated to the expected level on filecoin"
