### ISSUE TITLE
List of Storage Providers for Beta

### ISSUE THREAD

**Issue by TorfinnOlsen** [filecoin-project/motion#45]
Beta release is expected to support multiple storage providers for one instance of Motion at an ISV.

The ISV will need the ability to maintain a list of SP's and associate deals with them. 

User Story: As an ISV, I want the ability to select different Storage Providers for different customers, so that I  can leverage the Motion API to store their data with the appropriate Storage Provider based on the conditions I manage.

**Comment by masih** [comment]
* The definition of "the conditions" needs further expansion. Examples of such conditions would be very useful.
* There seem to be an assumption here that the ISV should control per customer. The  current motion API does not expose anything but a blob ID, i.e. there is no "customer" differentiator. We need a separate issue to capture the need for it, and that issue would be a pre-requisite to this one I think.

**Comment by celine3650** [comment]
It posed a risk

**Comment by celine3650** [comment]
Before we find a SP that meet SOC2 requirement for the ISV's client, we need to find a list of testing SP to test motion milestone2 by the end of August.

**Comment by celine3650** [comment]
Marina and Andrew mentioned they are going to start a SP pool program to source the SP that meet motion requirement. Close this as the risk is temporarily mitigated. Will follow up with them next week on the progress each week.
