### ISSUE TITLE
Motion / Singularity wallet integration

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/motion#54]
# What

When we create FIL wallet in motion, we should import the private key into singularity. There's an API endpoint on Singularity to import a private key. We'll also want to associate the returned Wallet ID with the dataset. There's a separate endpoint for this.

Requires https://github.com/data-preservation-programs/singularity/issues/218

**Comment by celine3650** [comment]
@elijaharita would like to learn about your latest progress on this item.

**Comment by elijaharita** [comment]
@celine3650 @hannahhoward this is the ticket you finished yourself with #76 right? is it clear to close?
