### ISSUE TITLE
Verify deal making and status round trip through singularity

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/motion#58]
This ticket is for a dev to spin up on their local machine:
- motion
- singularity API
- singularity workers
- boost dev net

And verify we can post a blob to motion that gets captured and prepared by singularity, which then makes a deal with boost decent. We should verify we can get a status on the deal once it's made through motion.

**Comment by celine3650** [comment]
Hannah tested it by 8/31 and it runned successfully.
